### ISSUE TITLE
"Less than" issue with the latex

### ISSUE THREAD

**Issue by DashingDave** [mgriebling/SwiftMathDemo#1]
For some reason, \\lt does not work for less than in the latex, so in ContentView.swift, just change

`MathView(equation: "\\left| \\vec{A} \\lt \\vec{B} \\right|...`
to
`MathView(equation: "\\left| \\vec{A} < \\vec{B} \\right|...`

**Comment by mgriebling** [comment]
LaTex naturally supports both the "<" and ">" symbols in math mode.
No backslash commands needed for either one (nor are they supported, currently).
There's no occurrence of "\\lt" in the released code.

**Comment by mgriebling** [comment]
Closed.
