### ISSUE TITLE
SwiftMath memory leak issue

### ISSUE THREAD

**Issue by petersktang** [mgriebling/SwiftMathDemo#2]
SwiftMath has memory leaks. Run the demo, and take a look at Memory Graph Hierarchy, MTFont, MTFontMathTable, MTMathAtom have very high counts.

<code>
  struct DummyView: View {
      var body: some View {
          NavigationStack {
              VStack {
                  NavigationLink("Show Detail View") {
                      ContentView()
                  }
              }
              .navigationTitle("Navigation")
          }
      }
  }
  struct DummyView_Previews: PreviewProvider {
      static var previews: some View {
          DummyView()
      }
  }
</code>

I created a DummyView invoked by the below

<code>
  @main
  struct SwiftMathDemoApp: App {
      var body: some Scene {
          WindowGroup {
              DummyView()
          }
      }
  }
</code>

Read the Memory Graph Hierarchy from debugger while on DummyView, the counts keep increasing every time I pop from ContentView back to DummyView.

**Comment by mgriebling** [comment]
Thanks, I'll have a look.

**Comment by petersktang** [comment]
Looks like the below change drastically reduced the memory leak, note the **weak** in front of *var font: MTFont*.
<code>
  class MTFontMathTable {
      // The font for this math table.
      weak var font:MTFont? // @property (nonatomic, readonly, weak) MTFont* font;
</code>

**Comment by mgriebling** [comment]
Thanks for looking into this.  I've been examining the code as well but so far nothing stands out.
I can make this change to the code.

**Comment by mgriebling** [comment]
Tweaked the `MTFont` `font` declaration a bit and don't see any more leaks.
